# Generated by Django 3.1 on 2020-08-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200819_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='default_article.jpg', upload_to='uploads/images'),
        ),
    ]
